### ISSUE TITLE
PyTorch 1.3 requires @staticmethods 

### ISSUE THREAD

**Issue by jk2569** [asappresearch/sru#111]
In cuda_functional.py, I manually added @staticmethod for the forward and backward in `cuda_functional.py` as in https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function

However, I'm still missing a Function somewhere as I have one more warning message:
`UserWarning: Legacy autograd function with non-static forward method is deprecated and will be removed in 1.3. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)`

and the error `AttributeError: 'Tensor' object has no attribute 'bidirectional'` which is most likely occurring due to the warning.

If you run the simple example in the ReadMe, I get the following error:
`/opt/conda/conda-bld/pytorch_1573049306803/work/torch/csrc/autograd/python_function.cpp:622: UserWarning: Legacy autograd function with non-static forward method is deprecated and will be removed in 1.3. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jk2569/.conda/envs/edwards/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jk2569/.conda/envs/edwards/lib/python3.7/site-packages/sru/sru_functional.py", line 564, in forward
    h, c = rnn(prevx, c0[i], mask_pad=mask_pad)
  File "/home/jk2569/.conda/envs/edwards/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jk2569/.conda/envs/edwards/lib/python3.7/site-packages/sru/sru_functional.py", line 386, in forward
    h, c = SRU_Compute(U, residual, self.weight_c, self.bias, c0)
  File "/home/jk2569/.conda/envs/edwards/lib/python3.7/site-packages/sru/cuda_functional.py", line 42, in forward
    bidir = 2 if self.bidirectional else 1
AttributeError: 'Tensor' object has no attribute 'bidirectional'`

I am on Linux and PyTorch 1.3.

**Comment by taoleicn** [comment]
The new sru release (version 2.2) should be compatible with PyTorch 1.3 now.
