### ISSUE TITLE
ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by baijintong** [asappresearch/sru#117]
Traceback (most recent call last):
  File "/home/omnisky/anaconda3/envs/demucsnew/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1030, in _build_extension_module
    check=True)
  File "/home/omnisky/anaconda3/envs/demucsnew/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/omnisky/anaconda3/envs/demucsnew/lib/python3.7/site-packages/sru/sru_functional.py", line 35, in _lazy_load_cuda_kernel
    from .cuda_functional import SRU_Compute_GPU
  File "/home/omnisky/anaconda3/envs/demucsnew/lib/python3.7/site-packages/sru/cuda_functional.py", line 14, in <module>
    verbose=False
  File "/home/omnisky/anaconda3/envs/demucsnew/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 661, in load
    is_python_module)
  File "/home/omnisky/anaconda3/envs/demucsnew/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 830, in _jit_compile
    with_cuda=with_cuda)
  File "/home/omnisky/anaconda3/envs/demucsnew/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 883, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "/home/omnisky/anaconda3/envs/demucsnew/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1043, in _build_extension_module
    raise RuntimeError(message)
RuntimeError: Error building extension 'sru_cuda_impl': [1/3] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=sru_cuda_impl -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/omnisky/anaconda3/envs/demucsnew/lib/python3.7/site-packages/torch/include -isystem /home/omnisky/anaconda3/envs/demucsnew/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/omnisky/anaconda3/envs/demucsnew/lib/python3.7/site-packages/torch/include/TH -isystem /home/omnisky/anaconda3/envs/demucsnew/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/omnisky/anaconda3/envs/demucsnew/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -std=c++11 -c /home/omnisky/anaconda3/envs/demucsnew/lib/python3.7/site-packages/sru/sru_cuda_kernel.cu -o sru_cuda_kernel.cuda.o
FAILED: sru_cuda_kernel.cuda.o 
/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=sru_cuda_impl -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/omnisky/anaconda3/envs/demucsnew/lib/python3.7/site-packages/torch/include -isystem /home/omnisky/anaconda3/envs/demucsnew/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/omnisky/anaconda3/envs/demucsnew/lib/python3.7/site-packages/torch/include/TH -isystem /home/omnisky/anaconda3/envs/demucsnew/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/omnisky/anaconda3/envs/demucsnew/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -std=c++11 -c /home/omnisky/anaconda3/envs/demucsnew/lib/python3.7/site-packages/sru/sru_cuda_kernel.cu -o sru_cuda_kernel.cuda.o
nvcc fatal   : Unsupported gpu architecture 'compute_75'
[2/3] c++ -MMD -MF sru_cuda_impl.o.d -DTORCH_EXTENSION_NAME=sru_cuda_impl -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/omnisky/anaconda3/envs/demucsnew/lib/python3.7/site-packages/torch/include -isystem /home/omnisky/anaconda3/envs/demucsnew/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/omnisky/anaconda3/envs/demucsnew/lib/python3.7/site-packages/torch/include/TH -isystem /home/omnisky/anaconda3/envs/demucsnew/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/omnisky/anaconda3/envs/demucsnew/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -O3 -c /home/omnisky/anaconda3/envs/demucsnew/lib/python3.7/site-packages/sru/sru_cuda_impl.cpp -o sru_cuda_impl.o
ninja: build stopped: subcommand failed.

**Comment by Coulson1026** [comment]
Hi,
I am having a same issue. Any updates? thanks!

**Comment by wpy3345** [comment]
Have u solved it ?

**Comment by PedestrianZQZ** [comment]
Same problem on me, has anyone solved this?

**Comment by Ritian-Li** [comment]
hi， have u solved it?

**Comment by PedestrianZQZ** [comment]
yes, i have solved it by replace the pytorch version to 1.6, python=3.7, you may have a try

**Comment by Ritian-Li** [comment]
> yes, i have solved it by replace the pytorch version to 1.6, python=3.7, you may have a try

yea, I have tried and it works, thanks dude
