### ISSUE TITLE
Run time error during forward pass of SRU

### ISSUE THREAD

**Issue by venkateshsathya** [asappresearch/sru#174]
I am running into this issue whenenver I do forward pass.
Have copied the error messages below. 
I have tried many things to get over this issue without success.
I tried installing via pip install and also directly including source code, and still see the issue.

Please let me know if you need any more details from my side to debug. 

>>> output_states, c_states = rnn(x)      # forward pass

Traceback (most recent call last):
  File "/home/vesathya/anaconda3/envs/SRUTrial/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1030, in _build_extension_module
    check=True)
  File "/home/vesathya/anaconda3/envs/SRUTrial/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vesathya/anaconda3/envs/SRUTrial/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/vesathya/anaconda3/envs/SRUTrial/lib/python3.7/site-packages/sru/modules.py", line 607, in forward
    h, c = rnn(prevx, c0_[i], mask_pad=mask_pad)
  File "/home/vesathya/anaconda3/envs/SRUTrial/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/vesathya/anaconda3/envs/SRUTrial/lib/python3.7/site-packages/sru/modules.py", line 261, in forward
    h, c = self.apply_recurrence(U, V, residual, c0, scale_val, mask_c, mask_pad)
  File "/home/vesathya/anaconda3/envs/SRUTrial/lib/python3.7/site-packages/sru/modules.py", line 284, in apply_recurrence
    self.amp_recurrence_fp16)
  File "/home/vesathya/anaconda3/envs/SRUTrial/lib/python3.7/site-packages/sru/ops.py", line 97, in elementwise_recurrence_gpu
    from .cuda_functional import SRU_Compute_GPU
  File "/home/vesathya/anaconda3/envs/SRUTrial/lib/python3.7/site-packages/sru/cuda_functional.py", line 14, in <module>
    verbose=False
  File "/home/vesathya/anaconda3/envs/SRUTrial/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 661, in load
    is_python_module)
  File "/home/vesathya/anaconda3/envs/SRUTrial/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 830, in _jit_compile
    with_cuda=with_cuda)
  File "/home/vesathya/anaconda3/envs/SRUTrial/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 883, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "/home/vesathya/anaconda3/envs/SRUTrial/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1043, in _build_extension_module
    raise RuntimeError(message)
RuntimeError: Error building extension 'sru_cuda_impl': [1/2] /usr/local/bin/nvcc -DTORCH_EXTENSION_NAME=sru_cuda_impl -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/vesathya/anaconda3/envs/SRUTrial/lib/python3.7/site-packages/torch/include -isystem /home/vesathya/anaconda3/envs/SRUTrial/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/vesathya/anaconda3/envs/SRUTrial/lib/python3.7/site-packages/torch/include/TH -isystem /home/vesathya/anaconda3/envs/SRUTrial/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/include -isystem /home/vesathya/anaconda3/envs/SRUTrial/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=sm_70 --compiler-options '-fPIC' -std=c++11 -c /home/vesathya/anaconda3/envs/SRUTrial/lib/python3.7/site-packages/sru/csrc/sru_cuda_kernel.cu -o sru_cuda_kernel.cuda.o
FAILED: sru_cuda_kernel.cuda.o 
/usr/local/bin/nvcc -DTORCH_EXTENSION_NAME=sru_cuda_impl -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/vesathya/anaconda3/envs/SRUTrial/lib/python3.7/site-packages/torch/include -isystem /home/vesathya/anaconda3/envs/SRUTrial/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/vesathya/anaconda3/envs/SRUTrial/lib/python3.7/site-packages/torch/include/TH -isystem /home/vesathya/anaconda3/envs/SRUTrial/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/include -isystem /home/vesathya/anaconda3/envs/SRUTrial/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=sm_70 --compiler-options '-fPIC' -std=c++11 -c /home/vesathya/anaconda3/envs/SRUTrial/lib/python3.7/site-packages/sru/csrc/sru_cuda_kernel.cu -o sru_cuda_kernel.cuda.o
sh: cicc: command not found
ninja: build stopped: subcommand failed.

**Comment by taoleicn** [comment]
hi @venkateshsathya , 

SRU uses a custom pytorch operator that has to be compiled just-in-time (JIT). `ninja`(https://github.com/ninja-build/ninja) is the build system used. See: https://pytorch.org/tutorials/advanced/cpp_extension.html

In your log, the error is "sh: cicc: command not found". and I could find some related posts via google:
https://forums.developer.nvidia.com/t/when-i-arch-option-error-sh-cicc-command-not-found-takes-place/31753
https://github.com/ShuangLI59/person_search/issues/56

Seems the issue is related to CUDA installation. Hope this would help.
