### ISSUE TITLE
internal error: unable to find __cudaPushCallConfiguration declaration. CUDA toolkit installation may be corrupt.

### ISSUE THREAD

**Issue by xianyu-123** [asappresearch/sru#194]
/home/wgj/anaconda3/bin/python /home/wgj/Pyedu/srutest.py
/home/wgj/anaconda3/lib/python3.8/site-packages/sru/cuda_functional.py:22: UserWarning: Just-in-time loading and compiling the CUDA kernels of SRU was unsuccessful. Got the following error:
Error building extension 'sru_cuda': [1/2] /home/wgj/anaconda3/bin/nvcc -DTORCH_EXTENSION_NAME=sru_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/wgj/anaconda3/lib/python3.8/site-packages/torch/include -isystem /home/wgj/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/wgj/anaconda3/lib/python3.8/site-packages/torch/include/TH -isystem /home/wgj/anaconda3/lib/python3.8/site-packages/torch/include/THC -isystem /home/wgj/anaconda3/include -isystem /home/wgj/anaconda3/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -c /home/wgj/anaconda3/lib/python3.8/site-packages/sru/csrc/sru_cuda_kernel.cu -o sru_cuda_kernel.cuda.o 
FAILED: sru_cuda_kernel.cuda.o 
/home/wgj/anaconda3/bin/nvcc -DTORCH_EXTENSION_NAME=sru_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/wgj/anaconda3/lib/python3.8/site-packages/torch/include -isystem /home/wgj/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/wgj/anaconda3/lib/python3.8/site-packages/torch/include/TH -isystem /home/wgj/anaconda3/lib/python3.8/site-packages/torch/include/THC -isystem /home/wgj/anaconda3/include -isystem /home/wgj/anaconda3/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -c /home/wgj/anaconda3/lib/python3.8/site-packages/sru/csrc/sru_cuda_kernel.cu -o sru_cuda_kernel.cuda.o 
/home/wgj/anaconda3/lib/python3.8/site-packages/sru/csrc/sru_cuda_kernel.cu(845): internal error: unable to find __cudaPushCallConfiguration declaration. CUDA toolkit installation may be corrupt.

1 catastrophic error detected in the compilation of "/home/wgj/anaconda3/lib/python3.8/site-packages/sru/csrc/sru_cuda_kernel.cu".
Compilation aborted.
ninja: build stopped: subcommand failed.

  warnings.warn("Just-in-time loading and compiling the CUDA kernels of SRU was unsuccessful. "
Traceback (most recent call last):
  File "/home/wgj/Pyedu/srutest.py", line 19, in <module>
    output_states, c_states = rnn(x)      # forward pass
  File "/home/wgj/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wgj/anaconda3/lib/python3.8/site-packages/sru/modules.py", line 634, in forward
    h, c = rnn(prevx, c0_[i], mask_pad=mask_pad)
  File "/home/wgj/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wgj/anaconda3/lib/python3.8/site-packages/sru/modules.py", line 276, in forward
    h, c = self.apply_recurrence(U, V, residual, c0, scale_val, mask_c, mask_pad)
  File "/home/wgj/anaconda3/lib/python3.8/site-packages/sru/modules.py", line 298, in apply_recurrence
    return elementwise_recurrence_gpu(U, residual, V, self.bias, c0,
  File "/home/wgj/anaconda3/lib/python3.8/site-packages/sru/ops.py", line 129, in elementwise_recurrence_gpu
    return ElementwiseRecurrence.apply(
  File "/home/wgj/anaconda3/lib/python3.8/site-packages/sru/cuda_functional.py", line 175, in forward
    h, last_hidden, c = elementwise_recurrence_forward(
RuntimeError: Caught an unknown exception!

Process finished with exit code 1

**Comment by Caihonghua** [comment]
Hi, have you solved this problem?

**Comment by xianyu-123** [comment]
您好，您的来信我已经收到，感谢您的来信!谢谢

**Comment by Caihonghua** [comment]
我已收到您的邮件，处理完后会尽快回复

**Comment by amituofo1996** [comment]
/home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/sru/cuda_functional.py:23: UserWarning: Just-in-time loading and compiling the CUDA kernels of SRU was unsuccessful. Got the following error:
Error building extension 'sru_cuda': [1/2] /usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=sru_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/torch/include -isystem /home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/torch/include/TH -isystem /home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/xf/miniconda3/envs/actor/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -c /home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/sru/csrc/sru_cuda_kernel.cu -o sru_cuda_kernel.cuda.o 
FAILED: sru_cuda_kernel.cuda.o 
/usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=sru_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/torch/include -isystem /home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/torch/include/TH -isystem /home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/xf/miniconda3/envs/actor/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -c /home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/sru/csrc/sru_cuda_kernel.cu -o sru_cuda_kernel.cuda.o 
nvcc fatal   : Value 'c++14' is not defined for option 'std'
ninja: build stopped: subcommand failed.

  warnings.warn("Just-in-time loading and compiling the CUDA kernels of SRU was unsuccessful. "
Traceback (most recent call last):
  File "/media/xf/F/code/VIBE-master/practice/pytorch_sru_practice.py", line 18, in <module>
    output_states, c_states = rnn(x)      # forward pass
  File "/home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/sru/modules.py", line 634, in forward
    h, c = rnn(prevx, c0_[i], mask_pad=mask_pad)
  File "/home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/sru/modules.py", line 276, in forward
    h, c = self.apply_recurrence(U, V, residual, c0, scale_val, mask_c, mask_pad)
  File "/home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/sru/modules.py", line 298, in apply_recurrence
    return elementwise_recurrence_gpu(U, residual, V, self.bias, c0,
  File "/home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/sru/ops.py", line 129, in elementwise_recurrence_gpu
    return ElementwiseRecurrence.apply(
  File "/home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/sru/cuda_functional.py", line 176, in forward
    h, last_hidden, c = elementwise_recurrence_forward(
RuntimeError: Caught an unknown exception!

**Comment by xianyu-123** [comment]
您好，您的来信我已经收到，感谢您的来信!谢谢

**Comment by Caihonghua** [comment]
我已收到您的邮件，处理完后会尽快回复

**Comment by amituofo1996** [comment]
I already install cuda，and set path value , but  still got this error

**Comment by skwskw0303** [comment]
D:\Users\skwsk\anaconda3\envs\skw\python.exe D:\wenxiandaima\ACRNN_EEG-main\ACRNN_EEG-main\main.py 
D:\wenxiandaima\ACRNN_EEG-main\ACRNN_EEG-main\module\sru\cuda_functional.py:23: UserWarning: Just-in-time loading and compiling the CUDA kernels of SRU was unsuccessful. Got the following error:
CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
  warnings.warn("Just-in-time loading and compiling the CUDA kernels of SRU was unsuccessful. "
(800, 384, 32)
(800,)
Traceback (most recent call last):
  File "D:\wenxiandaima\ACRNN_EEG-main\ACRNN_EEG-main\main.py", line 112, in <module>
    output = model(batch_x)
             ^^^^^^^^^^^^^^
  File "D:\Users\skwsk\anaconda3\envs\skw\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\wenxiandaima\ACRNN_EEG-main\ACRNN_EEG-main\ACRNN.py", line 46, in forward
    x_rn, x_c = self.sru(x_cn)  #[10,1,64] [10,1,64]
                ^^^^^^^^^^^^^^
  File "D:\Users\skwsk\anaconda3\envs\skw\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\wenxiandaima\ACRNN_EEG-main\ACRNN_EEG-main\module\sru\modules.py", line 634, in forward
    h, c = rnn(prevx, c0_[i], mask_pad=mask_pad)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\skwsk\anaconda3\envs\skw\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\wenxiandaima\ACRNN_EEG-main\ACRNN_EEG-main\module\sru\modules.py", line 276, in forward
    h, c = self.apply_recurrence(U, V, residual, c0, scale_val, mask_c, mask_pad)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\wenxiandaima\ACRNN_EEG-main\ACRNN_EEG-main\module\sru\modules.py", line 298, in apply_recurrence
    return elementwise_recurrence_gpu(U, residual, V, self.bias, c0,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\wenxiandaima\ACRNN_EEG-main\ACRNN_EEG-main\module\sru\ops.py", line 129, in elementwise_recurrence_gpu
    return ElementwiseRecurrence.apply(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\skwsk\anaconda3\envs\skw\Lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\wenxiandaima\ACRNN_EEG-main\ACRNN_EEG-main\module\sru\cuda_functional.py", line 176, in forward
    h, last_hidden, c = elementwise_recurrence_forward(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Caught an unknown exception!

Process finished with exit code 1
How to solve it?

**Comment by Caihonghua** [comment]
我已收到您的邮件，处理完后会尽快回复

**Comment by xianyu-123** [comment]
您好，您的来信我已经收到，感谢您的来信!谢谢

**Comment by zhiyuzhang-0212** [comment]
请问您解决了吗

**Comment by xianyu-123** [comment]
您好，您的来信我已经收到，感谢您的来信!谢谢

**Comment by zhiyuzhang-0212** [comment]
have you solved the problem?

**Comment by Caihonghua** [comment]
我已收到您的邮件，处理完后会尽快回复

**Comment by zhiyuzhang-0212** [comment]
> /home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/sru/cuda_functional.py:23: UserWarning: Just-in-time loading and compiling the CUDA kernels of SRU was unsuccessful. Got the following error: Error building extension 'sru_cuda': [1/2] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=sru_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -isystem /home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/torch/include -isystem /home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/torch/include/TH -isystem /home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/xf/miniconda3/envs/actor/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -c /home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/sru/csrc/sru_cuda_kernel.cu -o sru_cuda_kernel.cuda.o FAILED: sru_cuda_kernel.cuda.o /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=sru_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -isystem /home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/torch/include -isystem /home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/torch/include/TH -isystem /home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/xf/miniconda3/envs/actor/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -c /home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/sru/csrc/sru_cuda_kernel.cu -o sru_cuda_kernel.cuda.o nvcc fatal : Value 'c++14' is not defined for option 'std' ninja: build stopped: subcommand failed.
> 
> warnings.warn("Just-in-time loading and compiling the CUDA kernels of SRU was unsuccessful. " Traceback (most recent call last): File "/media/xf/F/code/VIBE-master/practice/pytorch_sru_practice.py", line 18, in output_states, c_states = rnn(x) # forward pass File "/home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl result = self.forward(*input, **kwargs) File "/home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/sru/modules.py", line 634, in forward h, c = rnn(prevx, c0_[i], mask_pad=mask_pad) File "/home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl result = self.forward(*input, **kwargs) File "/home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/sru/modules.py", line 276, in forward h, c = self.apply_recurrence(U, V, residual, c0, scale_val, mask_c, mask_pad) File "/home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/sru/modules.py", line 298, in apply_recurrence return elementwise_recurrence_gpu(U, residual, V, self.bias, c0, File "/home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/sru/ops.py", line 129, in elementwise_recurrence_gpu return ElementwiseRecurrence.apply( File "/home/xf/miniconda3/envs/actor/lib/python3.8/site-packages/sru/cuda_functional.py", line 176, in forward h, last_hidden, c = elementwise_recurrence_forward( RuntimeError: Caught an unknown exception!

have you solved the problem?

**Comment by zhiyuzhang-0212** [comment]
> Hi, have you solved this problem?

have you solved the problem?

**Comment by zhiyuzhang-0212** [comment]
> /home/wgj/anaconda3/bin/python /home/wgj/Pyedu/srutest.py /home/wgj/anaconda3/lib/python3.8/site-packages/sru/cuda_functional.py:22: UserWarning: Just-in-time loading and compiling the CUDA kernels of SRU was unsuccessful. Got the following error: Error building extension 'sru_cuda': [1/2] /home/wgj/anaconda3/bin/nvcc -DTORCH_EXTENSION_NAME=sru_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -isystem /home/wgj/anaconda3/lib/python3.8/site-packages/torch/include -isystem /home/wgj/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/wgj/anaconda3/lib/python3.8/site-packages/torch/include/TH -isystem /home/wgj/anaconda3/lib/python3.8/site-packages/torch/include/THC -isystem /home/wgj/anaconda3/include -isystem /home/wgj/anaconda3/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -c /home/wgj/anaconda3/lib/python3.8/site-packages/sru/csrc/sru_cuda_kernel.cu -o sru_cuda_kernel.cuda.o FAILED: sru_cuda_kernel.cuda.o /home/wgj/anaconda3/bin/nvcc -DTORCH_EXTENSION_NAME=sru_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -isystem /home/wgj/anaconda3/lib/python3.8/site-packages/torch/include -isystem /home/wgj/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/wgj/anaconda3/lib/python3.8/site-packages/torch/include/TH -isystem /home/wgj/anaconda3/lib/python3.8/site-packages/torch/include/THC -isystem /home/wgj/anaconda3/include -isystem /home/wgj/anaconda3/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -c /home/wgj/anaconda3/lib/python3.8/site-packages/sru/csrc/sru_cuda_kernel.cu -o sru_cuda_kernel.cuda.o /home/wgj/anaconda3/lib/python3.8/site-packages/sru/csrc/sru_cuda_kernel.cu(845): internal error: unable to find __cudaPushCallConfiguration declaration. CUDA toolkit installation may be corrupt.
> 
> 1 catastrophic error detected in the compilation of "/home/wgj/anaconda3/lib/python3.8/site-packages/sru/csrc/sru_cuda_kernel.cu". Compilation aborted. ninja: build stopped: subcommand failed.
> 
> warnings.warn("Just-in-time loading and compiling the CUDA kernels of SRU was unsuccessful. " Traceback (most recent call last): File "/home/wgj/Pyedu/srutest.py", line 19, in output_states, c_states = rnn(x) # forward pass File "/home/wgj/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl result = self.forward(*input, **kwargs) File "/home/wgj/anaconda3/lib/python3.8/site-packages/sru/modules.py", line 634, in forward h, c = rnn(prevx, c0_[i], mask_pad=mask_pad) File "/home/wgj/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl result = self.forward(*input, **kwargs) File "/home/wgj/anaconda3/lib/python3.8/site-packages/sru/modules.py", line 276, in forward h, c = self.apply_recurrence(U, V, residual, c0, scale_val, mask_c, mask_pad) File "/home/wgj/anaconda3/lib/python3.8/site-packages/sru/modules.py", line 298, in apply_recurrence return elementwise_recurrence_gpu(U, residual, V, self.bias, c0, File "/home/wgj/anaconda3/lib/python3.8/site-packages/sru/ops.py", line 129, in elementwise_recurrence_gpu return ElementwiseRecurrence.apply( File "/home/wgj/anaconda3/lib/python3.8/site-packages/sru/cuda_functional.py", line 175, in forward h, last_hidden, c = elementwise_recurrence_forward( RuntimeError: Caught an unknown exception!
> 
> Process finished with exit code 1

请问您解决了吗
