### ISSUE TITLE
Cannot import SRU

### ISSUE THREAD

**Issue by LXP-Never** [asappresearch/sru#196]
When I import sru, no error will be reported, but I will wait forever, I can only manually pause
```python
from sru import SRU

^CTraceback (most recent call last):
  File "/home/user/Desktop/Never_Ling/Anker_AI_SE/model/time_WaveCRN.py", line 12, in <module>
    from sru import SRU
  File "/home/user/anaconda3/envs/never_env/lib/python3.6/site-packages/sru/__init__.py", line 8, in <module>
    from sru.modules import SRU, SRUCell  # noqa: F401
  File "/home/user/anaconda3/envs/never_env/lib/python3.6/site-packages/sru/modules.py", line 11, in <module>
    from sru.ops import (elementwise_recurrence_inference,
  File "/home/user/anaconda3/envs/never_env/lib/python3.6/site-packages/sru/ops.py", line 9, in <module>
    from .cuda_functional import elementwise_recurrence_forward
  File "/home/user/anaconda3/envs/never_env/lib/python3.6/site-packages/sru/cuda_functional.py", line 20, in <module>
    verbose=False
  File "/home/user/anaconda3/envs/never_env/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1136, in load
    keep_intermediates=keep_intermediates)
  File "/home/user/anaconda3/envs/never_env/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1351, in _jit_compile
    baton.wait()
  File "/home/user/anaconda3/envs/never_env/lib/python3.6/site-packages/torch/utils/file_baton.py", line 42, in wait
    time.sleep(self.wait_seconds)
KeyboardInterrupt
```

**Comment by taolei87** [comment]
@LXP-Never this could be an issue with Just-In-Time compilation. 
Pytorch uses Ninja for [JIT loading](https://pytorch.org/docs/stable/cpp_extension.html#) of custom modules. You can try cleaning the temporary directory. 

The directory path depends on the platform and your setup. By default it is:
> **tmp**/torch_extensions/**name**, where **tmp** is the temporary folder on the current platform and **name** the name of the extension. e.g. `/tmp/torch_extensions/`

Also, you can set `verbose=True` to see additional debug information. Here is where to set it:
https://github.com/asappresearch/sru/blob/master/sru/cuda_functional.py#L20

**Comment by LXP-Never** [comment]
I deleted the contents of /home/user/.cache/torch_extensions in the directory, and it runs successfully now, thank you

**Comment by LXP-Never** [comment]
> @LXP-这永远不会是即时编译的问题。 Pytorch 使用 Ninja 进行自定义模块的[JIT 加载](https://pytorch.org/docs/stable/cpp_extension.html#)。您可以尝试清理临时目录。
> 
> 目录路径取决于平台和您的设置。默认情况下它是：
> 
> > **tmp** /torch_extensions/ **name**，其中**tmp**是当前平台上的临时文件夹，并**命名**扩展名。例如`/tmp/torch_extensions/`
> 
> 此外，您可以设置`verbose=True`查看其他调试信息。这是设置它的位置：[https](https://github.com/asappresearch/sru/blob/master/sru/cuda_functional.py#L20) : [//github.com/asappresearch/sru/blob/master/sru/cuda_functional.py#L20](https://github.com/asappresearch/sru/blob/master/sru/cuda_functional.py#L20)

我把目录下/home/user/.cache/torch_extensions的内容删除了，现在运行成功了，谢谢
