### ISSUE TITLE
 Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by WE1321254775** [asappresearch/sru#202]
I use version 2.6.0, but I encountered the following error
![Uploading image.png…]()

**Comment by WE1321254775** [comment]
D:\Anaconda\envs\taidi\lib\site-packages\torch\utils\cpp_extension.py:316: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
��Ϣ: ���ṩ��ģʽ�޷��ҵ��ļ���
D:\Anaconda\envs\taidi\lib\site-packages\sru\cuda_functional.py:24: UserWarning: Just-in-time loading and compiling the CUDA kernels of SRU was unsuccessful. Got the following error:
Command '['where', 'cl']' returned non-zero exit status 1.
  "Got the following error:\n" + str(e))
��Ϣ: ���ṩ��ģʽ�޷��ҵ��ļ���
Traceback (most recent call last):
  File "D:\Anaconda\envs\taidi\lib\site-packages\sru\cuda_functional.py", line 20, in <module>
    verbose=False
  File "D:\Anaconda\envs\taidi\lib\site-packages\torch\utils\cpp_extension.py", line 1136, in load
    keep_intermediates=keep_intermediates)
  File "D:\Anaconda\envs\taidi\lib\site-packages\torch\utils\cpp_extension.py", line 1347, in _jit_compile
    is_standalone=is_standalone)
  File "D:\Anaconda\envs\taidi\lib\site-packages\torch\utils\cpp_extension.py", line 1445, in _write_ninja_file_and_build_library
    is_standalone=is_standalone)
  File "D:\Anaconda\envs\taidi\lib\site-packages\torch\utils\cpp_extension.py", line 1885, in _write_ninja_file_to_build_library
    with_cuda=with_cuda)
  File "D:\Anaconda\envs\taidi\lib\site-packages\torch\utils\cpp_extension.py", line 2001, in _write_ninja_file
    'cl']).decode(*SUBPROCESS_DECODE_ARGS).split('\r\n')
  File "D:\Anaconda\envs\taidi\lib\subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "D:\Anaconda\envs\taidi\lib\subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

**Comment by wangxiao-star** [comment]
你解决了吗？

**Comment by w17786138647** [comment]
> 你解决了吗？

请问你解决了吗

**Comment by codesnoodles** [comment]
请问你解决了吗？

**Comment by wx-98** [comment]
> 请问你解决了吗？

解决了

**Comment by codesnoodles** [comment]
> 

方便说一下，解决方案是什么吗？谢谢。

**Comment by 1915982017** [comment]
> > 请问你解决了吗？
> 
> 解决了

能说一下，咋解决的吗？

**Comment by 1915982017** [comment]
> D:\Anaconda\envs\taidi\lib\site-packages\torch\utils\cpp_extension.py:316: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。 warnings.warn(f'Error checking compiler version for {compiler}: {error}') ��Ϣ: ���ṩ��ģʽ�޷��ҵ��ļ��� D:\Anaconda\envs\taidi\lib\site-packages\sru\cuda_functional.py:24: UserWarning: Just-in-time loading and compiling the CUDA kernels of SRU was unsuccessful. Got the following error: Command '['where', 'cl']' returned non-zero exit status 1. "Got the following error:\n" + str(e)) ��Ϣ: ���ṩ��ģʽ�޷��ҵ��ļ��� Traceback (most recent call last): File "D:\Anaconda\envs\taidi\lib\site-packages\sru\cuda_functional.py", line 20, in verbose=False File "D:\Anaconda\envs\taidi\lib\site-packages\torch\utils\cpp_extension.py", line 1136, in load keep_intermediates=keep_intermediates) File "D:\Anaconda\envs\taidi\lib\site-packages\torch\utils\cpp_extension.py", line 1347, in _jit_compile is_standalone=is_standalone) File "D:\Anaconda\envs\taidi\lib\site-packages\torch\utils\cpp_extension.py", line 1445, in _write_ninja_file_and_build_library is_standalone=is_standalone) File "D:\Anaconda\envs\taidi\lib\site-packages\torch\utils\cpp_extension.py", line 1885, in _write_ninja_file_to_build_library with_cuda=with_cuda) File "D:\Anaconda\envs\taidi\lib\site-packages\torch\utils\cpp_extension.py", line 2001, in _write_ninja_file 'cl']).decode(*SUBPROCESS_DECODE_ARGS).split('\r\n') File "D:\Anaconda\envs\taidi\lib\subprocess.py", line 376, in check_output **kwargs).stdout File "D:\Anaconda\envs\taidi\lib\subprocess.py", line 468, in run output=stdout, stderr=stderr) subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.
> 
> During handling of the above exception, another exception occurred:

你解决了吗

**Comment by wcycqjy** [comment]
要添加visual studio code里的cl.exe到系统变量
