### ISSUE TITLE
RuntimeError: Caught an unknown exception!

### ISSUE THREAD

**Issue by skwskw0303** [asappresearch/sru#209]
D:\Users\skwsk\anaconda3\envs\skw\python.exe D:\wenxiandaima\ACRNN_EEG-main\ACRNN_EEG-main\main.py
D:\wenxiandaima\ACRNN_EEG-main\ACRNN_EEG-main\module\sru\cuda_functional.py:23: UserWarning: Just-in-time loading and compiling the CUDA kernels of SRU was unsuccessful. Got the following error:
CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
warnings.warn("Just-in-time loading and compiling the CUDA kernels of SRU was unsuccessful. "
(800, 384, 32)
(800,)
Traceback (most recent call last):
File "D:\wenxiandaima\ACRNN_EEG-main\ACRNN_EEG-main\main.py", line 112, in
output = model(batch_x)
^^^^^^^^^^^^^^
File "D:\Users\skwsk\anaconda3\envs\skw\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\wenxiandaima\ACRNN_EEG-main\ACRNN_EEG-main\ACRNN.py", line 46, in forward
x_rn, x_c = self.sru(x_cn) #[10,1,64] [10,1,64]
^^^^^^^^^^^^^^
File "D:\Users\skwsk\anaconda3\envs\skw\Lib\site-packages\torch\nn\modules\module.py", line 1501, in call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\wenxiandaima\ACRNN_EEG-main\ACRNN_EEG-main\module\sru\modules.py", line 634, in forward
h, c = rnn(prevx, c0[i], mask_pad=mask_pad)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Users\skwsk\anaconda3\envs\skw\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\wenxiandaima\ACRNN_EEG-main\ACRNN_EEG-main\module\sru\modules.py", line 276, in forward
h, c = self.apply_recurrence(U, V, residual, c0, scale_val, mask_c, mask_pad)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\wenxiandaima\ACRNN_EEG-main\ACRNN_EEG-main\module\sru\modules.py", line 298, in apply_recurrence
return elementwise_recurrence_gpu(U, residual, V, self.bias, c0,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\wenxiandaima\ACRNN_EEG-main\ACRNN_EEG-main\module\sru\ops.py", line 129, in elementwise_recurrence_gpu
return ElementwiseRecurrence.apply(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Users\skwsk\anaconda3\envs\skw\Lib\site-packages\torch\autograd\function.py", line 506, in apply
return super().apply(*args, **kwargs) # type: ignore[misc]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\wenxiandaima\ACRNN_EEG-main\ACRNN_EEG-main\module\sru\cuda_functional.py", line 176, in forward
h, last_hidden, c = elementwise_recurrence_forward(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Caught an unknown exception!

Process finished with exit code 1
How to solve it?

**Comment by WanSheng-SZU** [comment]
你好，请问(800, 384, 32)数据是怎么得到的

**Comment by fallnlove** [comment]
Maybe it will be helpful to install CUDA 12.4 and run
`conda install nvidia/label/cuda-12.4.0::cuda`
And if it doesn't work yet you can try to install `gcc_linux-64` and `gxx_linux-64` packages
